// Main-process checks. Runs under Electron's Node (ELECTRON_RUN_AS_NODE) so
// better-sqlite3's Electron build loads; `electron` itself is stubbed (test/electron-stub.ts).
import './repositories/trash.check'
import './backup.check'
import './repositories/recurrence.check'
import './repositories/reminder.check'
import './settings.check'
import './repositories/link.check'
import './vault.check'
import '../mcp/mcp.check'
import './project.check'
import './brain.check'
import './claudeHook.check'
import './ics.check'
import './calendars.check'
